server:
  port: 8183

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: yoursUrl
      username: yoursUser
      password: yoursPass
      # 最小空闲连接数
      min-idle: 5
      # 最大连接数
      max-active: 10
      # 连接请求超时时间
      max-wait: 3000
      # 测试连接是否可用的查询语句
      validation-query: SELECT 1

  redis:
    port: yoursPort
    host: ******
    password: yoursPass

# 自定义百度aip信息
accountInfo:
  baidu:
    APP_ID: ******
    API_KEY: ******
    SECRET_KEY: ******
    IMAGE_TYPR: BASE64
    GROUP_ID: ******

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false